---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install Required Packages for Docker
      apt: name={{ item }} state=latest update_cache=yes force_apt_get=yes
      loop: [ 'apt-transport-https' , 'ca-certificates' , 'curl' , 'software-properties-common' , 'python3-pip' , 'virtualenv' , 'python3-setuptools' ]

    - name: Adding GPG key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adding Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Updating the apt
      apt: update_cache=yes

    - name: Installing Docker Ce
      apt: name=docker-ce state=latest

    - name: Installing a Python package for Docker
      pip:
        name: docker

    - name: Adding the current user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Pulling a Docker image
      docker_image:
        name: greengiant77/calc_api
        source: pull


    - name: ansible create directory example
      file:
        path: /home/ubuntu/cert
        state: directory

    - name: Copy cert test
      ansible.builtin.copy:
        src: /home/kali/cyber/projects/secure_rest_api/cert/cert.pem
        dest: /home/ubuntu/cert/cert.pem
        owner: root
        group: root
        mode: '0644'

    - name: Copy key
      ansible.builtin.copy:
        src: /home/kali/cyber/projects/secure_rest_api/cert/key.pem
        dest: /home/ubuntu/cert/key.pem
        owner: root
        group: root
        mode: '0644'

    - name: Starting a Docker image
      community.docker.docker_container:
        name: calc_api_container
        image: greengiant77/calc_api
        state: started
        restart: yes
        client_cert: /home/ubuntu/cert/cert.pem
        client_key: /home/ubuntu/cert/key.pem
        exposed_ports:
          - 5000
        ports:
          - "5000:5000"
